name: XinxinCustomMessage
version: '${project.version}'
main: ltd.dreamcraft.xinxincustommessage.XinxinCustomMessage
api-version: '1.13'
softdepend: [ XinxinBotApi,PlaceholderAPI,PokemonBag ]
commands:
  xinxincustommessage:
    aliases: [ xxcm ]